### ISSUE TITLE
Can't get TXError: funding failed validity check!

### ISSUE THREAD

**Issue by 99darwin** [Divicoin/Divi#7]
# Expected behavior
`divid` should start successfully and continue syncing the chain with a newly generated masternode
# Actual behavior
`divid` stops on initial execution with an error (see below)
# Operating system
Place an 'x' in the box next to your operating system
* [x] Mac OSX 10.13.1
* [x] Linux Ubuntu 16.04.4
* [x] Linux Ubuntu 17.04.4
* [x] Linux Ubuntu 18.04.4
* [x] Windows 10

# Steps to reproduce the problem
Go through the most recently documented steps to create a new masternode. After placing the long string generated by the `fundmasternode` command into `masternode.conf`, restarting `divid -debug` returns the following error:

```
init message: Loading masternode cache...
IS MASTER NODE
Can't get TXError: funding failed validity check!

Error: funding failed validity check!

PrepareShutdown: In progress...
Reindexing block file blk00000.dat...
CDBEnv::Flush : Flush(false)
CDBEnv::Flush : Flushing wallet.dat (refcount = 0)...
CDBEnv::Flush : wallet.dat checkpoint
CDBEnv::Flush : wallet.dat detach
CDBEnv::Flush : wallet.dat closed
CDBEnv::Flush : Flush(false) took               5ms
StopNode()
Committing 0 changed transactions (out of 0) to coin database...
CDBEnv::Flush : Flush(true)
CDBEnv::Flush : Flushing wallet.dat (refcount = 0)...
CDBEnv::Flush : wallet.dat checkpoint
CDBEnv::Flush : wallet.dat detach
CDBEnv::Flush : wallet.dat closed
CDBEnv::Flush : Flush(true) took               5ms
Shutdown: done
```

**NOTE**
Commenting out the long string in `masternode.conf` _will_ allow the wallet to start successfully and sync, but uncommenting the line after syncing brings back the funding validity error.

**Comment by MWaser** [comment]
So . . . . I’m just starting to get some traction on this . . . . .

 

Removing the line in the masternode.config works because you’ve removed the *claim* to the problematical funding.  Doing this (currently) leads to an empty-string tier masternode with all of the lack of capabilities never granted to that tier.  While disconcerting, this actually isn’t a problem (except for being confusing and brain-bending) because as an empty-string tier, it has neither rights nor privileges.  I am, of course, removing this possibility though.  (and, of course, this path should be ignored 😉)

 

What is disconcerting and problematical is that I am finding that not only is the master node not finding the funding (which might be a problem in our code) – but that the funding wallet is also no longer finding the funding at the same transaction address – which I haven’t yet run down the source of.  It is NOT that the money has been spent (that is a different error).  It is that it is claiming that a previously referenced transaction is no longer there.

 

A helpful test would be for you to verify that your funding node also no longer sees its original transaction – and then, if you’re up to the challenge – figuring out why . . . .   The last “divi-cli fundmasternode <alias> <tier> <transaction id> <masternode address>” should always be able to be repeated without error.  If the funds have been spent, it will say so.  What is disturbing is that it is saying that it can’t find the original funding transaction (even if was used for funding a live masternode for days . . . .).  I would have said that this is impossible except . . . . I now have a case of it as well with a node that ran for nearly a week before suddenly not having funding – and whose funding wallets still has running masternodes funded before and after it.  

 

So, here’s a challenge for all those wanting to run it down . . . . 

 

The funding code is the first couple of routines in rpc-masternode.cpp.  The core code is fundamentally unchanged from where it was originally pulled from the wallet code.  I would love to know how this code could possible lose track of a transaction that it acknowledged before (as did a lot of other code).  It might have something to do with re-indexing but . . . .
